services:
  rinhabackend: &rinhabackend
    networks:
      - backend
      - payment-processor
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    image: rinhabackend
    hostname: rinhabackend
    ports:
      - "3001:8080"
    build:
      context: .
      dockerfile: RinhaBackend/Dockerfile
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "140MB"
  
  rinhabackend-2:
    <<: *rinhabackend
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    container_name: rinhabackend-2
    ports:
      - "3002:8080"
    hostname: rinhabackend-2
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "140MB"

  postgres:
    image: postgres:16-alpine
    networks:
      - backend
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: payment
      POSTGRES_PASSWORD: "Postgres2022!"
    command: >-
      postgres -c max_connections=400
               -c shared_buffers=512MB
               -c synchronous_commit=off
               -c fsync=off
               -c full_page_writes=off
               -c wal_level=minimal
               -c max_wal_senders=0
               -c max_wal_size=4GB
               -c checkpoint_timeout=30min
               -c log_min_duration_statement=-1
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "40MB"

  load-balancer:
    container_name: load-balancer
    image: nginx:1.25-alpine
    depends_on:
      - rinhabackend
      - rinhabackend-2
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"



networks:
  backend:
    name: backend
    driver: bridge
  payment-processor:
    name: payment-processor
    driver: bridge
    external: true